### ISSUE TITLE
Store data in a more performant way

### ISSUE THREAD

**Issue by cldougl** [plotly/dash-sample-apps#136] opened 2019-06-05 18:56 UTC
# App name
All existing applications 

# Description of issue
With the current set up we're pushing this entire repo for each application deploy. In order to reduce unnecessary usage we should limit the data that is added to this repo and use alternative methods such as referencing files from the dataset repo or implementing mapped directory usage in these applications (I think using the dataset repo would be good because then users who want to copy the app code will have easy access to the dataset :) )

**Comment by lundstrj** [comment] 2020-01-31 20:12
Duplicate of #202

**Closed by lundstrj** 2020-01-31 20:12 UTC
Labels: dash, dashr, performance
